# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d62b4542f3d5b736f423470101d178e695fe71e7b823291ad68805cba7f811119de870b5a72daf65cc8716769e21750f8a2c0e735fca932373314750d4ada0

test:
  secret_key_base: 8a8fead2c256c57fdc71b1b01e5bb8f4d41ff4163b5d4ead030f25ac17d1da4b0f6471bd841f96888cadecafd518864ce876cc107a3c2521dc1972ab59bfbe93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
